// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRGfkHY-77gfLCF1hbm8p8I5y1NpR0wY',
    appId: '1:201577451114:web:1a5731210048b1f7994413',
    messagingSenderId: '201577451114',
    projectId: 'chat-app-11-f04b4',
    authDomain: 'chat-app-11-f04b4.firebaseapp.com',
    storageBucket: 'chat-app-11-f04b4.appspot.com',
    measurementId: 'G-CGNH8PBX4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWJNzBY8qaO0sf1iFFFCcmnNp_AQSjp4',
    appId: '1:201577451114:android:4d119b02fe6d336d994413',
    messagingSenderId: '201577451114',
    projectId: 'chat-app-11-f04b4',
    storageBucket: 'chat-app-11-f04b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnCVE22y2d4cUsJWkmDmDZCshgbCUeC4',
    appId: '1:201577451114:ios:18ac2e399447e426994413',
    messagingSenderId: '201577451114',
    projectId: 'chat-app-11-f04b4',
    storageBucket: 'chat-app-11-f04b4.appspot.com',
    iosBundleId: 'com.example.chatApp11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmnCVE22y2d4cUsJWkmDmDZCshgbCUeC4',
    appId: '1:201577451114:ios:03c8a7f0dc0091e3994413',
    messagingSenderId: '201577451114',
    projectId: 'chat-app-11-f04b4',
    storageBucket: 'chat-app-11-f04b4.appspot.com',
    iosBundleId: 'com.example.chatApp11.RunnerTests',
  );
}
